# Generated by Django 4.2.29 on 2026-08-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sql', models.TextField()),
                ('intent_text', models.TextField(blank=True, default='')),
                ('operation_type', models.CharField(max_length=50)),
                ('parsed_structure', models.JSONField(default=dict)),
                ('validation_result', models.JSONField(blank=True, default=dict)),
                ('intent_match', models.JSONField(blank=True, default=dict, null=True)),
                ('explanation', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='queries_que_created_583235_idx'), models.Index(fields=['operation_type'], name='queries_que_operati_660ccd_idx')],
            },
        ),
    ]
